/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NavBar {
    }
    interface SignIn {
    }
}
declare global {
    interface HTMLNavBarElement extends Components.NavBar, HTMLStencilElement {
    }
    var HTMLNavBarElement: {
        prototype: HTMLNavBarElement;
        new (): HTMLNavBarElement;
    };
    interface HTMLSignInElement extends Components.SignIn, HTMLStencilElement {
    }
    var HTMLSignInElement: {
        prototype: HTMLSignInElement;
        new (): HTMLSignInElement;
    };
    interface HTMLElementTagNameMap {
        "nav-bar": HTMLNavBarElement;
        "sign-in": HTMLSignInElement;
    }
}
declare namespace LocalJSX {
    interface NavBar {
    }
    interface SignIn {
    }
    interface IntrinsicElements {
        "nav-bar": NavBar;
        "sign-in": SignIn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nav-bar": LocalJSX.NavBar & JSXBase.HTMLAttributes<HTMLNavBarElement>;
            "sign-in": LocalJSX.SignIn & JSXBase.HTMLAttributes<HTMLSignInElement>;
        }
    }
}
